version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: TopicA:1:1, TopicB1:1:1, TopicB2:1:1, TopicC1:1:1, TopicC2:1:1, TopicC3:1:1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: kafka.controller=WARN,kafka.foo.bar=DEBUG
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR

  tests:
    build: .
    depends_on:
      - kafka
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx
    environment:
      DOTNET_ENVIRONMENT: Docker
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests/Forebag.Kafka.IntegrationTests/TestResults/}:/kafka/tests/Forebag.Kafka.IntegrationTests/TestResults
